### ISSUE TITLE
I did something with it!

### ISSUE THREAD

**Issue by martin-esparragoza** [UE2020/bufro#1]
oMG!11 I made  a REALLLLLLLY cooL gMAE wiTh ThIS epIC LiBRary 😂 😂 😂. https://diep.io IT tok mE thRE miNUTS tO makE thIS ! yOUr EpiC liBRary MaDe it SO faSt

**Comment by martin-esparragoza** [comment]
cHArNge LoG: ADDeD poW! nOw yOU canT plAy! 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂

**Comment by UE2020** [comment]
No kidding please.
